# Generated by Django 5.2.5 on 2025-08-28 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=200)),
                ('port', models.IntegerField(default=502)),
                ('unit_id', models.IntegerField(default=1)),
                ('enabled', models.BooleanField(default=True)),
                ('di_start', models.IntegerField(default=0)),
                ('di_count', models.IntegerField(default=0)),
                ('ir_start', models.IntegerField(default=0)),
                ('ir_count', models.IntegerField(default=0)),
                ('hr_start', models.IntegerField(default=0)),
                ('hr_count', models.IntegerField(default=0)),
                ('coil_start', models.IntegerField(default=0)),
                ('coil_count', models.IntegerField(default=0)),
                ('poll_interval_ms', models.IntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PollResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discrete_inputs', models.JSONField(default=list)),
                ('input_registers', models.JSONField(default=list)),
                ('holding_registers', models.JSONField(default=list)),
                ('coils', models.JSONField(default=list)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.TextField(blank=True, default='')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='modbusapp.modbusdevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
