# Generated by Django 5.2.5 on 2025-08-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbusapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdevice',
            name='hr_byte_order',
            field=models.CharField(choices=[('big', 'big'), ('little', 'little')], default='big', max_length=6),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='hr_data_type',
            field=models.CharField(choices=[('uint16', 'uint16 (per 1 reg)'), ('int16', 'int16 (per 1 reg)'), ('uint32', 'uint32 (per 2 regs)'), ('int32', 'int32 (per 2 regs)'), ('float32', 'float32 (per 2 regs)')], default='uint16', max_length=16),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='hr_datatype',
            field=models.CharField(choices=[('u16', 'Unsigned 16-bit'), ('s16', 'Signed 16-bit'), ('u32', 'Unsigned 32-bit'), ('s32', 'Signed 32-bit'), ('f32', 'Float 32-bit'), ('u64', 'Unsigned 64-bit'), ('s64', 'Signed 64-bit'), ('f64', 'Float 64-bit')], default='u16', max_length=3),
        ),
        migrations.AddField(
            model_name='modbusdevice',
            name='hr_word_order',
            field=models.CharField(choices=[('big', 'big'), ('little', 'little')], default='big', max_length=6),
        ),
    ]
