# Generated by Django 5.2.5 on 2025-08-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbusapp', '0002_modbusdevice_hr_byte_order_modbusdevice_hr_data_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modbusdevice',
            name='hr_data_type',
        ),
        migrations.AlterField(
            model_name='modbusdevice',
            name='hr_byte_order',
            field=models.CharField(choices=[('big', 'Big-endian'), ('little', 'Little-endian')], default='big', max_length=6),
        ),
        migrations.AlterField(
            model_name='modbusdevice',
            name='hr_word_order',
            field=models.CharField(choices=[('big', 'MSW first'), ('little', 'LSW first')], default='big', max_length=6),
        ),
    ]
