# Generated by Django 5.2.5 on 2025-08-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modbusapp', '0003_remove_modbusdevice_hr_data_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modbusdevice',
            name='hr_decimals',
            field=models.IntegerField(default=2),
        ),
    ]
