# Generated by Django on 2025-08-28
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modbusapp', '0005_modbuscard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModbusActionCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start', models.IntegerField(help_text='Starting coil address to write')),
                ('open_values', models.JSONField(default=list, help_text='List of booleans to write for OPEN')),
                ('close_values', models.JSONField(default=list, help_text='List of booleans to write for CLOSE')),
                ('order', models.IntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='modbusapp.modbusdevice')),
            ],
            options={
                'ordering': ['device_id', 'order', 'id'],
            },
        ),
    ]
